[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "coc-pylsp"
version = "0.1.0"
description = ""
authors = ["yaegassy <yosstools@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
python-lsp-server = "1.14.0"
